version: "3"

networks:
  docker-net:
    driver: bridge

services:
  postgres-db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "123123"
    ports:
      - "5432:5432"
    networks:
      - docker-net

  backend-server:
    build: .
    command: npm start
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/backend
      - /usr/backend/node_modules
    depends_on:
      - postgres-db

