version: "3"

networks:
  docker-net:
    driver: bridge

services:
  postgres-db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "123123"
    ports:
      - "5432:5432"
    networks:
      - docker-net
